/*
 * This source file was generated by the Gradle 'init' task
 */
package org.csu.cpsc;

import org.csu.cpsc.basic_data_structures.*;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        //MyListInterface<Integer> list = new MyArrayList<Integer>();
        MyListInterface<Integer> list = new MyLinkedList<Integer>();

        System.out.println("******Test add function******");
        list.add(2);
        list.add(4);
        list.add(6);
        list.add(8);


        System.out.println("******New ArrayList******");
        System.out.println(list.toString());

        System.out.println("******Test Contains function******");
        System.out.println(list.contains(1));
        System.out.println(list.contains(4));

        System.out.println("******Test Size Function******");
        System.out.println(list.size());

        System.out.println("******Test get function******");
        System.out.println(list.get(1));

        System.out.println("******Test index of******");
        System.out.println(list.indexOf(6));
        System.out.println(list.indexOf(3));

         System.out.println("******Test Set Function******");
         list.set(1, 10);
         System.out.println(list.get(1));

        System.out.println("******Test remove******");
        System.out.println("List before remove: " + list.toString());
        //System.out.println(list.remove(2));
        list.remove(0);
        System.out.println("List after remove: " + list.toString());

        System.out.println("******Test add******");
        System.out.println("List before add: " + list.toString());
        //System.out.println(list.remove(2));
        list.add(2, 12);
        System.out.println("List after add: " + list.toString());
    }

}


/*
 This source file was generated by the Gradle 'init' task

package org.csu.cpsc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //MyListinterface<Integer> list = new MylinkedList,Integer>();
        //list.add(2);
        //list.add(4);
        //list.add(6);

        //System.out.println();

        //System.out.println(list.size());

        MyStack<String> stack = new MyStack<>();

        String word = "racecar";

        for(String c : word.split(regex:"")){
            stack.push(c);
        }

        System.out.println(stack.peek());

        //Setup a loop that goes until the stack is empty
        while (! stack.empty()){
            newWord = newWord + stack.pop();
        }
        if(word.equals(newWord)){
            System.out.prinltln(word + "is a valid palindrom");
        } else {
            System.out.println(word + "is not valid");
        }
        
    }
}
*/
