/*
 * This source file was generated by the Gradle 'init' task
 */
package org.csu.cpsc.basic_data_structures ;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //MyListinterface<Integer> list = new MylinkedList,Integer>();
        //list.add(2);
        //list.add(4);
        //list.add(6);

        //System.out.println();

        //System.out.println(list.size());

        MyStack<String> stack = new MyStack<>();

        String word = "racecar";

        for(String c : word.split(regex:"")){
            stack.push(c);
        }

        System.out.println(stack.peek());

        //Setup a loop that goes until the stack is empty
        while (! stack.empty()){
            newWord = newWord + stack.pop();
        }
        if(word.equals(newWord)){
            System.out.prinltln(word + "is a valid palindrom");
        } else {
            System.out.println(word + "is not valid");
        }
        
    }
}
